### ISSUE TITLE
Namespace/Annotation field and autocomplete workflow requirements

### ISSUE THREAD

**Issue by wshayes** [OpenBEL/belmgr#27]
Evidence json:
- BELMgr needs human readable content for Annotation field (e.g. Type=Species  Value=Human or Homo sapiens) to fill out edit form

Annotation/Namespace search results:
- Human and machine formats for Namespace/AnnotationType and ID/Label in search results
- match text (already available)
- Namespace results - information on _links.item[].type - are they equivalents or orthologs or ...?

Having to follow the _links.collection to get the collection name and prefix would necessitate many additional http queries for a single autocomplete request impacting the user experience

**Comment by abargnesi** [comment]
Regarding the evidence resource the annotations are present under the `experiment_context` property. [This gist](https://gist.github.com/abargnesi/aa77b30235cf757ec688#file-evidence-json-L15-L20) shows an experiment_context object with _name_/_value_. This response should also have conveyed the annotation's URI so I'll investigate why it does not.

Would the following experiment_context object be sufficient? This will allow you to present human-readable values and the identifier you can use on save.

``` json
{
    "experiment_context": [
        {
            "name": "Ncbi Taxonomy",
            "value": "Homo sapiens",
            "_links": {
                "self": {
                    "type": "annotation_value",
                    "href": "http://next.belframework.org/api/annotations/ncbi-taxonomy/values/9606"
                }
            }
        }
    ]
}
```

---

Adding the _namespace_ and _annotation_ resource to the respective value resource is a great idea, since they will frequently be used together. What about extending _annotation_value_ and _namespace_value_ resources to include _annotation_ and _namespace_ respectively? These will be included by default.

Example for Ncbi Taxonomy / Homo sapiens:

``` json
{
    "annotation_value": {
        "type": "SpeciesAnnotationConcept",
        "identifier": "9606",
        "name": "Homo sapiens",
        "annotation": {
            "name": "Ncbi Taxonomy",
            "prefix": "taxon",
            "domain": "species"
        },
        "_links": {
            "self": {
                "type": "annotation_value",
                "href": "http://next.belframework.org/api/annotations/ncbi-taxonomy/values/9606"
            },
            "collection": {
                "type": "annotation",
                "href": "http://next.belframework.org/api/annotations/ncbi-taxonomy"
            }
        }
    }
}
```

---

Regarding the _namespace_value_collection_ links for a _namespace_value_ resource I agree we should change these. Maybe something descriptive like _namespace_value_equivalents_ and _namespace_value_orthologs_?

**Comment by wshayes** [comment]
Those example JSON responses look good and fit the need well.  Using 'namespace_value_equivalents', etc to indicate the type of item works well.  

What would be saved in the experiment_context of the BEL Evidence?  Does the first JSON example get round-tripped back to the POST/PUT for that Evidence? maybe with a minimal form of

```
            "_links": {
                "self": {
                    "type": "annotation_value",
                    "href": "http://next.belframework.org/api/annotations/ncbi-taxonomy/values/9606"
                }
            }
```

**Comment by abargnesi** [comment]
The documentation for how _experiment_context_ is mapped is lacking so I'll make a note.

The first example can be round-tripped using POST/PUT on that evidence link.

Each object in the _experiment_context_ can have either _name_/_value_ properties or a _uri_ property. The [evidence.schema.json](http://next.belframework.org/schemas/evidence.schema.json) describes the expected schema.

**Comment by wshayes** [comment]
Perfect - thanks!

**Comment by abargnesi** [comment]
On second thought the original evidence's Species annotation would not have a _uri_ because _Species_ does not map to the [Ncbi Taxonomy](http://next.belframework.org/api/annotations/taxon).

However [this evidence](http://next.belframework.org/api/evidence/564b215738da0d280d000002) does have annotations with _uri_ properties when they map correctly:

``` json
...
"experiment_context": [
    {
        "name": "Ncbi Taxonomy",
        "value": "Homo sapiens",
        "uri": "http://next.belframework.org/api/annotations/taxon/values/9606"
    },
    {
        "name": "CellularStructures",
        "value": "Cell Nucleus"
    },
    {
        "name": "Mesh Anatomy",
        "value": "Muscle, Smooth, Vascular",
        "uri": "http://next.belframework.org/api/annotations/mesha/values/D009131"
    }
],
...
```

**Comment by wshayes** [comment]
Very happy to shift to the NCBI Taxonomy and drop Species - this gains us the identifiers.org RDF mapping as well.

**Comment by abargnesi** [comment]
Deployed enhancement to next.belframework.org to address OpenBEL/openbel-server#38.

How do they look?

Affected routes with example:
- Single value
  - http://next.belframework.org/api/annotations/do/values/silicosis
- Value search across all annotations
  - http://next.belframework.org/api/annotations/values?filter={%22category%22:%22fts%22,%22name%22:%22search%22,%22value%22:%22lung%22}
- Value search within an annotation
  - http://next.belframework.org/api/annotations/do/values?filter={%22category%22:%22fts%22,%22name%22:%22search%22,%22value%22:%22lung%22}

**Comment by wshayes** [comment]
These look very good.  What URI should I use for the Evidence.json?  The self href?  Thanks!

**Comment by abargnesi** [comment]
Yes. The `self` link with type `annotation_value`.

**Comment by abargnesi** [comment]
Would you mind if I moved this issue to the openbel-server project?

**Comment by wshayes** [comment]
Nope and it's ready to close as far as I'm concerned.

**Comment by abargnesi** [comment]
This issue was moved to OpenBEL/openbel-server#90

**Comment by abargnesi** [comment]
Wow, +1 for https://github-issue-mover.appspot.com/.
